# Default values for dealservice
replicaCount: 1

image:
  repository: default-route-openshift-image-registry.apps.rm2.thpm.p1.openshiftapps.com/garethpark-dev/dealservice
  tag: 0.0.1-SNAPSHOT
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:h2:mem:dealsdb"
  - name: SPRING_DATASOURCE_USERNAME
    value: "sa"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "password"

# OpenShift specific settings
openshift:
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect 