{{- if .Values.openshift.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "dealservice.fullname" . }}
  labels:
    {{- include "dealservice.labels" . | nindent 4 }}
spec:
  host: {{ .Values.openshift.route.host | default (printf "%s.%s" (include "dealservice.fullname" .) .Release.Namespace) }}
  to:
    kind: Service
    name: {{ include "dealservice.fullname" . }}
    weight: 100
  {{- if .Values.openshift.route.tls.enabled }}
  tls:
    termination: {{ .Values.openshift.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.openshift.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
{{- end }} 