{{- if .Values.openshift.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "dealservice.fullname" . }}
  labels:
    {{- include "dealservice.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "dealservice.fullname" . }}
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }} 