apiVersion: v1
kind: Service
metadata:
  name: {{ include "dealservice.fullname" . }}
  labels:
    {{- include "dealservice.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "dealservice.selectorLabels" . | nindent 4 }} 